# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RestaurantManager_DATN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RestaurantManager_DATN
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Core'
	pod 'FirebaseStorage'
	pod 'Material'
	pod 'ObjectMapper'
	pod 'Kingfisher'
end
